name: .NET

on:
  push:
    branches: [ feature/backend, feature/ui, master, bug/* ]
  pull_request:
    branches: [ feature/backend, feature/ui, master, bug/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./TrafficManagementCenter.Server
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./TrafficManagementCenter.Server
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./TrafficManagementCenter.Server
